import Head from "next/head";
import HeroMain from "../Components/HeroSection/HeroMain";
import Movies from "../Components/Movies/Movies";
import { HeroImageParallex } from "../Components/HeroSection/HeroImageParallex";
import InfoCard from "../Components/HeroSection/InfoCard";
import MidHeroMovieSection from "../Components/HeroSection/MidHeroMovieSection";
import Navbar from "../Components/Navbar/Navbar";
import getServerSideProps from "../middleware/helpers";
import { useDispatch } from "react-redux";
import {
  getUsersWatchlist,
  WatchlistActions,
} from "../Store/StateSlices/watchlistSlice";
import { loginStateActions } from "../Store/StateSlices/loginSlice";
import { useEffect } from "react";

export default function Home(props) {
  const dispatch = useDispatch();
  useEffect(() => {
    if (props.isUserloggedIn === true) {
      dispatch(loginStateActions.UserLoggedIn());
      dispatch(getUsersWatchlist());
    } else {
      dispatch(loginStateActions.UserLoggedOut());
      dispatch(WatchlistActions.emptyWatchlist());
    }
  }, [dispatch, props.isUserloggedIn]);
  return (
    <>
      <Navbar />
      <div className="w-full">
        <Head>
          <title>Movies Saga</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <HeroImageParallex />
        <HeroMain />
        <InfoCard />
        <MidHeroMovieSection />
        <h1 className="sm:text-3xl text-3xl font-medium title-font mb-2 text-white pl-10 md:pl-16 pt-20">
          Top trending
        </h1>
        <div className="h-1 w-20 bg-white rounded ml-16"></div>
        <Movies />
      </div>
    </>
  );
}

export { getServerSideProps };
